services:
  - type: web
    name: orcax-franchise-api
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri
      - key: EMAIL_USER
        value: your-gmail
      - key: EMAIL_PASS
        value: your-gmail-app-password
      - key: EMAIL_RECEIVER
        value: receiver@email.com
      - key: EMAIL_SERVICE
        value: gmail
